Repository brain-tec/commission, pull requests merged in 2020-05, with the labels that each got.

#47 Syncing from upstream OCA/commission (12.0)
  sale_commission/i18n/it.po
Labels: 12.0

#48 [t117026] Commission with Pricelist
  sale_commission_pricelist/models/sale_order.py
Labels: 11.0, bug

#49 Syncing from upstream OCA/commission (12.0)
  sale_commission/i18n/es.po
Labels: 12.0

#50 Syncing from upstream OCA/commission (13.0)
  .pre-commit-config.yaml
Labels: 13.0

#51 Syncing from upstream OCA/commission (12.0)
  sale_commission/README.rst
  sale_commission/readme/ROADMAP.rst
  sale_commission/static/description/index.html
Labels: 12.0
